import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'

const storageKey = 'lesson-ledger:pricing:v1'
async function fillHours(page: Page, name: string, value: string, groupId = 0, gradeId = 0) {
  for (const target of [`group-${groupId}`, `grade-${gradeId}`]) {
    const button = page.locator(`button[aria-controls="${target}"]`)
    if (await button.getAttribute('aria-expanded') === 'false') await button.click()
  }
  await page.getByRole('textbox', { name, exact: true }).fill(value)
}
async function calculate(page: Page) { await page.getByRole('button', { name: '计算课时费', exact: true }).click() }
async function settings(page: Page) { await page.getByRole('button', { name: '计费设置', exact: true }).click() }
const firstPrice = (page: Page) => page.getByRole('textbox', { name: '第1阶梯一至五年级单价', exact: true })

test.beforeEach(async ({ page }) => { await page.goto('/') })

test('计费说明独立只读，入口直接打开弹窗并恢复焦点', async ({ page }, info) => {
  const help = page.getByRole('button', { name: '计费说明', exact: true })
  await expect(help).toHaveCount(1)
  await expect(page.getByRole('button', { name: '计费设置', exact: true })).toHaveCount(1)
  await expect(page.getByRole('heading', { name: '课时费是怎么算的？' })).toHaveCount(0)
  await fillHours(page, '一年级一对一小时数', '10')
  await calculate(page)
  const originalUrl = page.url()
  await help.click()
  const explanation = page.getByRole('dialog', { name: '计费说明', exact: true })
  await expect(explanation).toBeVisible()
  expect(page.url()).toBe(originalUrl)
  await expect(explanation.getByRole('textbox')).toHaveCount(0)
  const rates = explanation.getByRole('table', { name: '当前计费阶梯表' })
  await expect(rates.locator('tbody tr')).toHaveCount(6)
  await expect(rates.locator('tbody td')).toHaveCount(24)
  await expect(rates.locator('tbody td').first()).toHaveText('15.00')
  await expect(explanation.getByRole('heading', { name: '当前计费阶梯表' })).toBeInViewport()
  await expect(explanation.getByRole('button', { name: '修改阶梯表' })).toBeInViewport()
  await expect(explanation.getByRole('button', { name: '保存并应用' })).toHaveCount(0)
  await expect(explanation).toContainText('先计入一对一，再计入一对二，最后计入一对三')
  await expect(explanation).toContainText('每条最终明细四舍五入到分')
  await expect(page.getByRole('dialog', { name: '计费设置', exact: true })).toHaveCount(0)
  const close = explanation.getByRole('button', { name: '关闭计费说明' })
  await expect(close).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(explanation.getByRole('button', { name: '我知道了' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(close).toBeFocused()
  expect(await explanation.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: `test-results/${info.project.name}-billing-help.png` })
  await page.keyboard.press('Escape')
  await expect(explanation).toHaveCount(0)
  await expect(help).toBeFocused()
  await help.click()
  await page.getByRole('button', { name: '我知道了' }).click()
  await expect(help).toBeFocused()
  await expect(page.getByTestId('total-fee')).toHaveText('¥150.00')
  await expect(page.locator('.stale-notice')).toHaveCount(0)
  await expect(page.getByRole('textbox', { name: '一年级一对一小时数', exact: true })).toHaveValue('10')
  expect(await page.evaluate(key => localStorage.getItem(key), storageKey)).toBeNull()
  await settings(page)
  const editor = page.getByRole('dialog', { name: '计费设置', exact: true })
  await expect(editor.getByRole('textbox')).toHaveCount(24)
  await expect(editor.getByRole('button', { name: '保存并应用' })).toBeVisible()
  await expect(explanation).toHaveCount(0)
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.locator('.stale-notice')).toHaveCount(0)
})

test('从说明阶梯表切换设置，取消不改价，保存后展示当前价格而非旧快照', async ({ page }) => {
  await fillHours(page, '一年级一对一小时数', '10')
  await calculate(page)
  const help = page.getByRole('button', { name: '计费说明', exact: true })
  const explanation = page.getByRole('dialog', { name: '计费说明', exact: true })
  const editor = page.getByRole('dialog', { name: '计费设置', exact: true })
  const currentPrice = explanation.getByRole('table', { name: '当前计费阶梯表' }).locator('tbody td').first()
  await help.click()
  await explanation.getByRole('button', { name: '修改阶梯表' }).click()
  await expect(explanation).toHaveCount(0)
  await expect(editor).toBeVisible()
  await expect(page.locator('dialog[open]')).toHaveCount(1)
  expect(await page.evaluate(() => document.body.style.overflow)).toBe('hidden')
  expect(await editor.evaluate(el => el.contains(document.activeElement))).toBe(true)
  await firstPrice(page).fill('20')
  await editor.getByRole('button', { name: '取消', exact: true }).click()
  await expect(help).toBeFocused()
  expect(await page.evaluate(() => document.body.style.overflow)).toBe('')
  await expect(page.locator('.stale-notice')).toHaveCount(0)
  await help.click()
  await expect(currentPrice).toHaveText('15.00')
  await explanation.getByRole('button', { name: '修改阶梯表' }).click()
  await firstPrice(page).fill('20')
  await editor.getByRole('button', { name: '保存并应用' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(help).toBeFocused()
  await expect(page.locator('.stale-notice')).toBeVisible()
  await expect(page.getByTestId('snapshot-price-0-0')).toHaveText('15.00')
  await expect(page.getByTestId('total-fee')).toHaveText('¥150.00')
  await help.click()
  await expect(currentPrice).toHaveText('20.00')
  await page.keyboard.press('Escape')
  await settings(page)
  await expect(firstPrice(page)).toHaveValue('20')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '计费设置', exact: true })).toBeFocused()
  await calculate(page)
  await expect(page.getByTestId('total-fee')).toHaveText('¥200.00')
})

test('A01：空状态、零课时和完整计费表；无整页横向溢出', async ({ page }, info) => {
  await expect(page.getByRole('heading', { name: '月度课时费计算器' })).toBeVisible()
  await expect(page.getByText('填写课时后点击计算', { exact: true })).toBeVisible()
  await page.screenshot({ path: `test-results/${info.project.name}-initial.png`, fullPage: true })
  await calculate(page)
  await expect(page.getByTestId('total-fee')).toHaveText('¥0.00')
  await expect(page.getByText('本月暂无授课').first()).toBeVisible()
  await expect(page.getByTestId('snapshot-rates').locator('tbody tr')).toHaveCount(6)
  await expect(page.getByTestId('snapshot-rates').locator('tbody td')).toHaveCount(24)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('A04/A11：双向实时换算，未完成小数、精度和零值显示', async ({ page }) => {
  const lessonInput = page.getByRole('textbox', { name: '一年级一对一节数', exact: true })
  const hourInput = page.getByRole('textbox', { name: '一年级一对一小时数', exact: true })
  await lessonInput.fill('25')
  await expect(hourInput).toHaveValue('50')
  await calculate(page)
  await expect(page.getByTestId('total-fee')).toHaveText('¥1,650.00')
  await hourInput.fill('3')
  await expect(lessonInput).toHaveValue('1.5')
  await hourInput.fill('0.01')
  await expect(lessonInput).toHaveValue('0.005')
  await hourInput.fill('2.')
  await expect(hourInput).toHaveValue('2.')
  await expect(lessonInput).toHaveValue('0.005')
  await hourInput.press('Tab')
  await expect(hourInput).toHaveValue('2')
  await expect(lessonInput).toHaveValue('1')
  await hourInput.fill('0')
  await hourInput.press('Tab')
  await expect(hourInput).toHaveValue('')
  await expect(lessonInput).toHaveValue('')
})

test('A07/A14/B10：反向录入、多人班跨阶梯、快照内容与公式', async ({ page }, info) => {
  await fillHours(page, '初三一对三小时数', '30', 2, 8)
  await fillHours(page, '六年级一对二小时数', '20', 1, 5)
  await fillHours(page, '一年级一对一小时数', '20')
  await calculate(page)
  await expect(page.getByTestId('total-fee')).toHaveText('¥5,330.00')
  await expect(page.locator('.tier-amount')).toHaveText(['¥600.00', '¥3,300.00', '¥1,430.00', '¥0.00', '¥0.00', '¥0.00'])
  await expect(page.getByText('20 × 90 × 1.3', { exact: true })).toBeVisible()
  await expect(page.getByTestId('snapshot-rates')).toContainText('每节 2 小时')
  await expect(page.getByTestId('snapshot-rates')).toContainText('先计入一对一，再计入一对二，最后计入一对三')
  await expect(page.getByTestId('snapshot-rates')).toContainText('配置版本：默认价格 v1')
  const unused = page.locator('.tier-details').last()
  await unused.locator('summary').click()
  await expect(unused.getByText('本阶梯未使用')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: `test-results/${info.project.name}-settlement.png`, fullPage: true })
})

test('B01/B03/B08：保存价格、旧结果保留旧表、重算、刷新仅保留价格', async ({ page }) => {
  // Insecure LAN HTTP contexts may not expose randomUUID; pricing must still save.
  await page.evaluate(() => Object.defineProperty(crypto, 'randomUUID', { value: undefined }))
  await fillHours(page, '一年级一对一小时数', '10')
  await calculate(page)
  await settings(page)
  await firstPrice(page).fill('20')
  await page.getByRole('button', { name: '保存并应用' }).click()
  await expect(page.getByText('输入或规则已变化，请重新计算。下方明细和计费表为上次计算快照。')).toBeVisible()
  await expect(page.getByTestId('total-fee')).toHaveText('¥150.00')
  await expect(page.getByTestId('snapshot-price-0-0')).toHaveText('15.00')
  await calculate(page)
  await expect(page.getByTestId('total-fee')).toHaveText('¥200.00')
  await expect(page.getByTestId('snapshot-price-0-0')).toHaveText('20.00')
  await expect(page.locator('.stale-notice')).toHaveCount(0)
  expect(await page.evaluate(key => Object.keys(localStorage).filter(k => k === key || k.includes('lesson')), storageKey)).toEqual([storageKey])
  await page.reload()
  await expect(page.getByTestId('total-fee')).toHaveText('¥—')
  await expect(page.getByRole('textbox', { name: '一年级一对一小时数', exact: true })).toHaveValue('')
  await settings(page)
  await expect(firstPrice(page)).toHaveValue('20')
})

test('B02/B06：取消丢弃草稿；恢复默认需确认并保存', async ({ page }) => {
  await settings(page)
  await firstPrice(page).fill('20')
  await page.getByRole('button', { name: '保存并应用' }).click()
  await fillHours(page, '一年级一对一小时数', '10')
  await calculate(page)
  await settings(page)
  await firstPrice(page).fill('99')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.locator('.stale-notice')).toHaveCount(0)
  await expect(page.getByTestId('total-fee')).toHaveText('¥200.00')
  await settings(page)
  await expect(firstPrice(page)).toHaveValue('20')
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: '恢复默认价格' }).click()
  await expect(firstPrice(page)).toHaveValue('20')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '恢复默认价格' }).click()
  await expect(firstPrice(page)).toHaveValue('15')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await settings(page)
  await expect(firstPrice(page)).toHaveValue('20')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '恢复默认价格' }).click()
  await page.getByRole('button', { name: '保存并应用' }).click()
  await calculate(page)
  await expect(page.getByTestId('total-fee')).toHaveText('¥150.00')
  await expect(page.getByTestId('snapshot-price-0-0')).toHaveText('15.00')
})

test('B04：无效课时阻止计算并定位折叠区域里的错误', async ({ page }) => {
  await fillHours(page, '一年级一对一小时数', '10')
  await calculate(page)
  for (const value of ['-1', '文字', 'Infinity', '0.001']) {
    await fillHours(page, '六年级一对一小时数', value, 1, 5)
    await page.locator('button[aria-controls="group-1"]').click()
    await calculate(page)
    await expect(page.getByRole('textbox', { name: '六年级一对一小时数', exact: true })).toBeFocused()
    await expect(page.getByRole('textbox', { name: '六年级一对一小时数', exact: true })).toHaveAttribute('aria-invalid', 'true')
    await expect(page.getByTestId('total-fee')).toHaveText('¥150.00')
    await expect(page.locator('body')).not.toContainText('NaN')
  }
  await fillHours(page, '六年级一对一小时数', '0.01', 1, 5)
  await calculate(page)
  await expect(page.getByTestId('total-fee')).toHaveText('¥150.25')
})

test('B05：24 单价校验、零元有效；设置面板适配窄屏', async ({ page }, info) => {
  await settings(page)
  await expect(page.getByRole('dialog').getByRole('textbox')).toHaveCount(24)
  for (const value of ['', '-1', 'abc', '0.001']) {
    await firstPrice(page).fill(value)
    await page.getByRole('button', { name: '保存并应用' }).click()
    await expect(firstPrice(page)).toBeFocused()
    await expect(firstPrice(page)).toHaveAttribute('aria-invalid', 'true')
  }
  await firstPrice(page).fill('0')
  await page.getByRole('textbox', { name: '第6阶梯高二、高三单价', exact: true }).scrollIntoViewIfNeeded()
  await expect(page.getByText('元／小时 · 一对一基准', { exact: true })).toBeInViewport()
  if (info.project.name === 'mobile') {
    await expect(page.getByRole('region', { name: '第6阶梯价格', exact: true }).getByRole('heading')).toBeInViewport()
  } else {
    await expect(page.locator('.price-editor-header')).toBeInViewport()
  }
  await firstPrice(page).scrollIntoViewIfNeeded()
  expect(await page.getByRole('dialog').evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth)).toBe(true)
  await page.screenshot({ path: `test-results/${info.project.name}-settings.png` })
  await page.getByRole('button', { name: '保存并应用' }).click()
  await fillHours(page, '一年级一对一小时数', '10')
  await calculate(page)
  await expect(page.getByTestId('total-fee')).toHaveText('¥0.00')
})

test('B07：本地结构损坏，不覆盖损坏原值；显式保存可恢复', async ({ page }) => {
  await page.evaluate(key => localStorage.setItem(key, '{broken'), storageKey)
  await page.reload()
  await expect(page.getByText('本地配置不可用，当前使用默认价格，请核对')).toBeVisible()
  expect(await page.evaluate(key => localStorage.getItem(key), storageKey)).toBe('{broken')
  await settings(page)
  await expect(firstPrice(page)).toHaveValue('15')
  await page.getByRole('button', { name: '保存并应用' }).click()
  await expect(page.getByText('本地配置不可用，当前使用默认价格，请核对')).toHaveCount(0)
  await page.reload()
  await expect(page.getByText('本地配置不可用，当前使用默认价格，请核对')).toHaveCount(0)
})

test('B07：存储读取失败可正常使用默认配置', async ({ page }) => {
  await page.addInitScript(() => { Storage.prototype.getItem = () => { throw new DOMException('denied', 'SecurityError') } })
  await page.reload()
  await expect(page.getByText('本地配置不可用，当前使用默认价格，请核对')).toBeVisible()
  await fillHours(page, '一年级一对一小时数', '10')
  await calculate(page)
  await expect(page.getByTestId('total-fee')).toHaveText('¥150.00')
})

test('B07：保存失败保留草稿与生效配置，仅本次使用须主动点击', async ({ page }) => {
  await fillHours(page, '一年级一对一小时数', '10')
  await calculate(page)
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('full', 'QuotaExceededError') } })
  await settings(page)
  await firstPrice(page).fill('20')
  await page.getByRole('button', { name: '保存并应用' }).click()
  await expect(page.getByRole('alert')).toContainText('保存失败')
  await expect(firstPrice(page)).toHaveValue('20')
  await expect(page.getByTestId('total-fee')).toHaveText('¥150.00')
  await expect(page.getByTestId('snapshot-price-0-0')).toHaveText('15.00')
  await page.getByRole('button', { name: '仅本次使用（刷新后不保留）' }).click()
  await expect(page.getByText('当前价格仅本次使用，刷新后不会保留。')).toBeVisible()
  await calculate(page)
  await expect(page.getByTestId('total-fee')).toHaveText('¥200.00')
  await page.reload()
  await settings(page)
  await expect(firstPrice(page)).toHaveValue('15')
})

test('B09：月份与课时变化标记待重算，月份保留输入但不改变价格', async ({ page }) => {
  await fillHours(page, '一年级一对一小时数', '10')
  await calculate(page)
  await fillHours(page, '一年级一对一小时数', '20')
  await expect(page.locator('.stale-notice')).toBeVisible()
  await expect(page.getByTestId('total-fee')).toHaveText('¥150.00')
  await calculate(page)
  await expect(page.getByTestId('total-fee')).toHaveText('¥300.00')
  await page.getByLabel('结算月份', { exact: true }).fill('2025-08')
  await expect(page.locator('.month-notice')).toContainText('课时尚未清空')
  await expect(page.locator('.stale-notice')).toBeVisible()
  await expect(page.getByRole('textbox', { name: '一年级一对一小时数', exact: true })).toHaveValue('20')
  await calculate(page)
  await expect(page.locator('.summary-top')).toContainText('2025 年 8 月')
  await expect(page.getByTestId('total-fee')).toHaveText('¥300.00')
})

test('清空有输入时确认；保留月份与价格；Esc 关闭设置并返回焦点', async ({ page }) => {
  await page.getByLabel('结算月份', { exact: true }).fill('2025-08')
  await fillHours(page, '一年级一对一小时数', '10')
  await calculate(page)
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: '清空课时' }).click()
  await expect(page.getByTestId('total-fee')).toHaveText('¥150.00')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '清空课时' }).click()
  await expect(page.getByTestId('total-fee')).toHaveText('¥—')
  await expect(page.getByLabel('结算月份', { exact: true })).toHaveValue('2025-08')
  await settings(page)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '计费设置', exact: true })).toBeFocused()
})
